language: node_js

node_js:
  - 14

branches:
  only:
  - master

cache:
  directories:
    - "node_modules"

script:
  - set -e
  - npm run lint
  - npm run test:unit

after_success:
  - npm run coveralls
