service: twilio-gatekeeper

provider:
  name: aws
  runtime: nodejs8.10

functions:
  authorize:
    handler: src/handler.authorize
    events:
      - http:
          path: authorize
          method: post
          integration: lambda
          response:
            headers:
              Content-Type: "'application/xml'"
            template: $input.path("$")
  hello:
    handler: src/handler.hello
    events:
      - http:
          path: hello
          method: post
          integration: lambda
          response:
            headers:
              Content-Type: "'application/xml'"
            template: $input.path("$")
  version:
    handler: src/handler.version
    events:
      - http:
          path: version
          method: get
          integration: lambda

plugins:
  - serverless-domain-manager

custom:
  customDomain:
    domainName: gatekeeper.jonathanfoster.io
    certificateName: "*.jonathanfoster.io"
    createRoute53Record: true
