service: twilio-gatekeeper

provider:
  name: aws
  runtime: nodejs6.10
  profile: jonathan@jonathanfoster

functions:
  health:
    handler: src/handler.health
    events:
      - http:
          path: health
          method: get
          integration: lambda

  hello:
    handler: src/handler.hello
    events:
      - http:
          path: hello
          method: post
          integration: lambda
          response:
            headers:
              Content-Type: "'application/xml'"
            template: $input.path("$")

plugins:
  - serverless-domain-manager

custom:
  customDomain:
    domainName: gatekeeper.jonathanfoster.io
    certificateName: '*.jonathanfoster.io'
    createRoute53Record: true
