service: twilio-gatekeeper

provider:
  name: aws
  runtime: nodejs6.10
  profile: jonathan@jonathanfoster

functions:
  hello:
    handler: src/handler.hello
    events:
      - http:
          path: hello
          method: get
          integration: lambda
          cors: true

plugins:
  - serverless-domain-manager

custom:
  customDomain:
    domainName: gatekeeper.jonathanfoster.io
    certificateName: '*.jonathanfoster.io'
    createRoute53Record: true
